In [2]:
import pandas as pd

In [3]:
portfolio_summ =  pd.read_excel('Data/PortfolioSummary.xls')

In [4]:
portfolio_summ.columns

Index(['Federal Student Aid Portfolio Summary', 'Unnamed: 1', 'Unnamed: 2',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8', 'Unnamed: 9'],
      dtype='object')

In [5]:
new_header = ["Year","Quarter",'Direct Loans','DL Recipients',
'FFEL','FFEl Recipients',
'Perkins','Perkins Recipients',
'Total loans','Total Recipients']

In [6]:
portfolio_summ = portfolio_summ[5:]
portfolio_summ.columns = new_header
portfolio_summ

,Year,Quarter,Direct Loans,DL Recipients,FFEL,FFEl Recipients,Perkins,Perkins Recipients,Total loans,Total Recipients
5,2007,NaN,106.8,7,401.9,22.6,8.2,2.8,516,28.3
6,2008,NaN,122.5,7.7,446.5,23.7,8.5,2.9,577,29.9
7,2009,NaN,154.9,9.2,493.3,25,8.7,3,657,32.1
8,2010,NaN,224.5,14.4,516.7,25.1,8.4,2.9,749.8,34.3
9,2011,NaN,350.1,19.4,489.8,23.8,8.3,2.9,848.2,36.5
10,2012,NaN,488.3,22.8,451.7,22.4,8.2,2.9,948.2,38.3
11,2013,Q1,508.7,23.4,444.9,22.1,8.2,3,961.9,38.7
12,NaN,Q2,553,24.1,437,21.6,8.3,3,998.6,38.9
13,NaN,Q3,569.2,24.3,429.5,21.2,8.2,2.9,1006.8,38.7
14,NaN,Q4,609.1,25.6,423,20.9,8.1,2.9,1040.2,39.6
15,2014,Q1,626.5,26.2,417.1,20.6,8.2,3,1051.8,40
16,NaN,Q2,669,26.5,409.7,20.2,8.3,3,1087,40
17,NaN,Q3,685.7,26.7,402.5,19.8,8.2,2.9,1096.5,39.9
18,NaN,Q4,726.6,27.9,395,19.4,8.2,2.9,1129.8,40.7
19,2015,Q1,744.3,28.5,387.6,19.1,8.2,3,1140.1,41.1
20,NaN,Q2,787,28.7,379.1,18.6,8.3,2.9,1174.4,41
21,NaN,Q3,803.1,28.8,370.9,18.2,8.2,2.9,1182.1,40.8
22,NaN,Q4,840.7,29.9,363.6,17.9,8.1,2.8,1212.4,41.6
23,2016,Q1,854.8,30.3,357.3,17.5,8.1,2.9,1220.3,41.8
24,NaN,Q2,896.6,30.5,350.2,17.2,8.2,2.8,1254.9,41.7
25,NaN,Q3,911.6,30.5,342.6,16.8,8,2.7,1262.2,41.5
26,NaN,Q4,949.1,31.5,335.2,16.4,7.9,2.7,1292.2,42.3
27,2017,Q1,963.5,31.9,328.3,16.1,7.9,2.7,1299.7,42.4
28,NaN,Q2,1003.3,32.1,320.5,15.7,7.9,2.6,1331.7,42.3
29,NaN,Q3,1017,32,312.6,15.2,7.8,2.6,1337.4,42
30,NaN,Q4,1053.5,33,305.8,14.9,7.6,2.5,1366.9,42.6
31,2018,Q1,1066.8,33.3,301.1,14.5,7.6,2.5,1375.5,42.8
32,NaN,Q2,1104,33.4,295.5,14.2,7.6,2.5,1407.1,42.6
33,NaN,Q3,1116,33.3,288.6,13.8,7.4,2.4,1412,42.2
34,NaN,Q4,1150.3,34.2,281.8,13.5,7.1,2.3,1439.2,42.9
35,2019,Q1,1163.3,34.5,277,13.1,6.9,2.2,1447.1,43
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,1 Totals may not equal the sum of Direct Loans...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,2 Data is run at the end of the corresponding ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,3 Recipient is the student that benefits from ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
portfolio_summ = portfolio_summ[:-5]

In [8]:
portfolio_summ = portfolio_summ.fillna(method='ffill')

In [9]:
portfolio_summ = portfolio_summ.drop(columns=['Quarter'])

In [10]:
portfolio_summ = portfolio_summ.reset_index(drop=True)
portfolio_summ

,Year,Direct Loans,DL Recipients,FFEL,FFEl Recipients,Perkins,Perkins Recipients,Total loans,Total Recipients
0,2007,106.8,7.0,401.9,22.6,8.2,2.8,516.0,28.3
1,2008,122.5,7.7,446.5,23.7,8.5,2.9,577.0,29.9
2,2009,154.9,9.2,493.3,25.0,8.7,3.0,657.0,32.1
3,2010,224.5,14.4,516.7,25.1,8.4,2.9,749.8,34.3
4,2011,350.1,19.4,489.8,23.8,8.3,2.9,848.2,36.5
5,2012,488.3,22.8,451.7,22.4,8.2,2.9,948.2,38.3
6,2013,508.7,23.4,444.9,22.1,8.2,3.0,961.9,38.7
7,2013,553.0,24.1,437.0,21.6,8.3,3.0,998.6,38.9
8,2013,569.2,24.3,429.5,21.2,8.2,2.9,1006.8,38.7
9,2013,609.1,25.6,423.0,20.9,8.1,2.9,1040.2,39.6
10,2014,626.5,26.2,417.1,20.6,8.2,3.0,1051.8,40.0
11,2014,669.0,26.5,409.7,20.2,8.3,3.0,1087.0,40.0
12,2014,685.7,26.7,402.5,19.8,8.2,2.9,1096.5,39.9
13,2014,726.6,27.9,395.0,19.4,8.2,2.9,1129.8,40.7
14,2015,744.3,28.5,387.6,19.1,8.2,3.0,1140.1,41.1
15,2015,787.0,28.7,379.1,18.6,8.3,2.9,1174.4,41.0
16,2015,803.1,28.8,370.9,18.2,8.2,2.9,1182.1,40.8
17,2015,840.7,29.9,363.6,17.9,8.1,2.8,1212.4,41.6
18,2016,854.8,30.3,357.3,17.5,8.1,2.9,1220.3,41.8
19,2016,896.6,30.5,350.2,17.2,8.2,2.8,1254.9,41.7
20,2016,911.6,30.5,342.6,16.8,8.0,2.7,1262.2,41.5
21,2016,949.1,31.5,335.2,16.4,7.9,2.7,1292.2,42.3
22,2017,963.5,31.9,328.3,16.1,7.9,2.7,1299.7,42.4
23,2017,1003.3,32.1,320.5,15.7,7.9,2.6,1331.7,42.3
24,2017,1017.0,32.0,312.6,15.2,7.8,2.6,1337.4,42.0
25,2017,1053.5,33.0,305.8,14.9,7.6,2.5,1366.9,42.6
26,2018,1066.8,33.3,301.1,14.5,7.6,2.5,1375.5,42.8
27,2018,1104.0,33.4,295.5,14.2,7.6,2.5,1407.1,42.6
28,2018,1116.0,33.3,288.6,13.8,7.4,2.4,1412.0,42.2
29,2018,1150.3,34.2,281.8,13.5,7.1,2.3,1439.2,42.9
30,2019,1163.3,34.5,277.0,13.1,6.9,2.2,1447.1,43.0

In [11]:
yearly_portfolio_summ = portfolio_summ.groupby(['Year']).sum()
yearly_portfolio_summ

,Direct Loans,DL Recipients,FFEL,FFEl Recipients,Perkins,Perkins Recipients,Total loans,Total Recipients
Year,,,,,,,,
2007,106.8,7.0,401.9,22.6,8.2,2.8,516.0,28.3
2008,122.5,7.7,446.5,23.7,8.5,2.9,577.0,29.9
2009,154.9,9.2,493.3,25.0,8.7,3.0,657.0,32.1
2010,224.5,14.4,516.7,25.1,8.4,2.9,749.8,34.3
2011,350.1,19.4,489.8,23.8,8.3,2.9,848.2,36.5
2012,488.3,22.8,451.7,22.4,8.2,2.9,948.2,38.3
2013,2240.0,97.4,1734.4,85.8,32.8,11.8,4007.5,155.9
2014,2707.8,107.3,1624.3,80.0,32.9,11.8,4365.1,160.6
2015,3175.1,115.9,1501.2,73.8,32.8,11.6,4709.0,164.5
2016,3612.1,122.8,1385.3,67.9,32.2,11.1,5029.6,167.3
2017,4037.3,129.0,1267.2,61.9,31.2,10.4,5335.7,169.3
2018,4437.1,134.2,1167.0,56.0,29.7,9.7,5633.8,170.5
2019,1163.3,34.5,277.0,13.1,6.9,2.2,1447.1,43.0

In [12]:
yearly_portfolio_summ.dtypes

Direct Loans          float64
DL Recipients         float64
FFEL                  float64
FFEl Recipients       float64
Perkins               float64
Perkins Recipients    float64
Total loans           float64
Total Recipients      float64
dtype: object

In [13]:
yearly_portfolio_summ.to_csv('clean_data/yearly_portfolio_summary.csv', index=True)